---
- name: ensure needed folders exist
  file: path={{ appsearch_folder }}/{{ item }} state=directory follow=yes
  with_items:
    - log
    - data

- name: set up Java path for version > 4.x
  set_fact: java_home="/usr/lib/jvm/java-8-openjdk-amd64/"
  when: not ( appsearch_version < "5.0.0" )

- name: download AppSearch for version > 7.x
  get_url:
    url: https://appsearch.elastic.co/downloads/app-search/app-search-{{ appsearch_version }}.tar.gz
    dest: "{{ appsearch_folder }}/app-search-{{ appsearch_version }}.tar.gz"

- name: extract AppSearch
  unarchive:
    src: "{{ appsearch_folder }}/app-search-{{ appsearch_version }}.tar.gz"
    dest: "{{ appsearch_folder }}/"
    remote_src: True

- name: move AppSearch folder to this final destination
  shell: cp -rTf {{ appsearch_folder }}/app-search-{{ appsearch_version }} {{ appsearch_folder }}/{{ appsearch_name }} && rm -rf {{ appsearch_folder }}/app-search-{{ appsearch_version }}

- name: send AppSearch config for AppSearch
  template:
    src:  app-search.yml
    dest: "{{ appsearch_folder }}/{{ appsearch_name }}/config/app-search.yml"

- name: send AppSearch config
  template:
    src:  app-search.conf
    dest: "{{ supervisor_folder }}/conf.d/{{ appsearch_name }}.conf"

- name: reload Supervisor config to launch AppSearch
  command: "{{ supervisor_bin }}/supervisorctl update"
