## ===================== Elastic App Search Configuration =====================
#
# NOTE: Elastic App Search comes with reasonable defaults.
#       Before adjusting the configuration, make sure you understand what you
#       are trying to accomplish and the consequences.
#
# NOTE: For passwords, the use of environment variables is encouraged
#       to keep values from being written to disk, e.g.
#       elasticsearch.password: ${ELASTICSEARCH_PASSWORD:changeme}
#
# ---------------------------------- Elasticsearch ----------------------------
#
# App Search needs one-time permission to alter Elasticsearch settings.
# Ensure the Elasticsearch settings are correct, then set the following to true.
# Or, adjust Elasticsearch's config/elasticsearch.yml instead.
# See README.md for more details.
#
allow_es_settings_modification: true
#
# Elasticsearch full cluster URL:
#
elasticsearch.host: http://{{ loopback_adress }}:{{ elastic_port }}
#
# Elasticsearch credentials:
#
elasticsearch.username: {{ elastic_user }}
elasticsearch.password: {{ elastic_pass }}
#
# Elasticsearch SSL settings:
#
#elasticsearch.ssl.enabled: false
#elasticsearch.ssl.certificate:
#elasticsearch.ssl.certificate_authority:
#elasticsearch.ssl.key:
#elasticsearch.ssl.key_passphrase:
#elasticsearch.ssl.verify: true
#
# ------------------------------- Hosting & Network ---------------------------
#
# Define the exposed URL at which users will reach App Search.
# Defaults to localhost:3002 for testing purposes.
# Most cases will use one of:
#
# * An IP: http://255.255.255.255
# * A FQDN: http://example.com
# * Shortname defined via /etc/hosts: http://app-search.search
#
app_search.external_url: https://{{ appsearch_fqdn }}

# Web application listen_host and listen_port.
# Your application will run on this host and port.
#
# * app_search.listen_host: Must be a valid IPv4 or IPv6 address.
# * app_search.listen_port: Must be a valid port number (1-65535).
#
app_search.listen_host: {{ loopback_adress }}
app_search.listen_port: {{ appsearch_port }}
#
# Background worker monitoring.
# Diagnostic information will be served on `app_search.monitoring_port`.
#
# * app_search.monitoring_enabled: Set to false to disableÂ monitoring.
# * app_search.monitoring_port: Must be a valid port number (1-65535).
#
app_search.monitoring_enabled: false
app_search.monitoring_port: {{ appsearch_monit_port }}
#
# ------------------------------ Authentication -------------------------------
#
# The origin of authenticated App Search users.
# Options are standard, elasticsearch-native, and elasticsearch-saml.
#
# Docs: https://swiftype.com/documentation/app-search/self-managed/security
#
# * standard: Users are created within the App Search dashboard.
# * elasticsearch-native: Users are managed via the Elasticsearch native realm.
# * elasticsearch-saml: Users are managed via the Elasticsearch SAML realm.
#
app_search.auth.source: elasticsearch-native
#
# (SAML only) Name of the realm within the Elasticsearch realm chain.
#
#app_search.auth.name:
#
# ---------------------------------- Email -----------------------------------
#
# Connect App Search to a mailer.
# Docs: https://swiftype.com/documentation/app-search/self-managed/configuration
#
#email.account.enabled: true
#email.account.smtp.auth: plain
#email.account.smtp.starttls.enable: false
#email.account.smtp.host: 127.0.0.1
#email.account.smtp.port: 25
#email.account.smtp.user:
#email.account.smtp.password:
#email.account.email_defaults.from: {{ ansible_user }}@occitech.eu
#
# ----------------------------------- APIs ------------------------------------
#
# Set to true hide product version information from API responses.
#
#hide_version_info: false
#
# ----------------------------- Diagnostics report ----------------------------
#
# Path where diagnostic reports will be generated.
#
#diagnostic_report_directory: diagnostics
#
# ---------------------------------- Logging ----------------------------------
#
# Choose your log export path.
#
#log_directory: log
#
# Log level can be: debug, info, warn, error, fatal, or unknown.
#
#log_level: info
#
# Choose your Filebeat logs export path.
#
#filebeat_log_directory: log
#
# ------------------------------- TLS/SSL -------------------------------
#
# Configure TLS/SSL encryption.
#
#app_search.ssl.enabled: false
#app_search.ssl.keystore.path:
#app_search.ssl.keystore.password:
#app_search.ssl.keystore.key_password:
#app_search.ssl.redirect_http_from_port:
#
# Worker monitoring server ssl options
#
#app_search.monitoring_ssl.enabled: false
#app_search.monitoring_ssl.certificate:
#app_search.monitoring_ssl.certificate_authority:
#app_search.monitoring_ssl.key:
#app_search.monitoring_ssl.key_passphrase:
#app_search.monitoring_ssl.verify: true
#
# ---------------------------------- Session ----------------------------------
#
# Set key to persist user sessions through process restarts.
#
#secret_session_key:
#